// Generated by Wrangler
// After running `wrangler types`, regenerate this file by running `npx wrangler types`
interface Env {
  // Add your bindings here, e.g.:
  // MY_KV_NAMESPACE: KVNamespace;
  // MY_DURABLE_OBJECT: DurableObjectNamespace;
  // MY_BUCKET: R2Bucket;
  // MY_SERVICE: Fetcher;
  // MY_QUEUE: Queue;
  // MY_DB: D1Database;
}
